wallpaper {
    monitor = desc:Thermotrex Corporation TL140VDXP10
    path = ~/Pictures/backgrounds/new/room.jpg
    fit_mode = cover
}

wallpaper {
    monitor = desc:Samsung Electric Company LS24AG32x H9JW105851
    path = ~/Pictures/backgrounds/new/spaceship.jpg
    fit_mode = fill
}

wallpaper {
    monitor = desc:Hewlett Packard HP E241i CN44171KK9
    path = ~/Pictures/backgrounds/vertical/cuntryside_rain.jpeg
    fit_mode = fill
}

