{
  inputs,
  pkgs,
  config,
  ...
}:
{
  home.packages = with pkgs; [
    httrack
    brave
    signal-desktop
    prismlauncher
    discord
    spotify
    wineWowPackages.waylandFull
    firefox
    inputs.zen-browser.packages."${pkgs.stdenv.hostPlatform.system}".twilight
    mnemosyne
    lutris
  ];
}
