# yazi.toml
[mgr]
show_hidden = true
show_symlink = true
linemode = 'mtime'
sort_by = "extension"
sort_dir_first = true

[preview]
wrap = "yes"

[opener]
edit = [ 
    { run = 'nvim "$@"', block = true, for = 'unix', desc = "nvim file" },
]

open = [
    { run = 'xdg-open "$@"', block = false, orphan = true, desc = "open with xdg-open", for = "linux" },
    { run = 'zathura "$@"', block = false, orphan = true, desc = "open pdf with zathura", for = "linux" },
    { run = 'evince "$@"', block = false, orphan = true, desc = "open pdf with evince", for = "linux" },
    { run = 'zen "$@"', block = false, orphan = true, desc = "open html in zen", for = "linux" },
]

[open]
rules = [
    { mime = "text/*",          use = ["edit", "open"] },
    { mime = "application/pdf", use = ["open"] },
    { mime = "text/html",       use = ["open"] },
    { mime = "*",               use = ["edit", "open"] },
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
