# yazi.toml
[mgr]
show_hidden = true
show_symlink = true
linemode = 'mtime'
sort_by = "extension"
sort_dir_first = true

[preview]
wrap = "yes"

[opener]
edit = [
    { run = 'nvim %s', block = true, for = 'unix', desc = "nvim file" },
]

open = [
    { run = 'xdg-open %s', orphan = true, desc = "open with xdg-open", for = "linux" },
]

pdf = [
    { run = 'zathura %s', orphan = true, desc = "open pdf with zathura", for = "linux" },
    { run = 'evince %s', orphan = true, desc = "open pdf with evince", for = "linux" },
]

html = [
    { run = 'zen %s', orphan = true, desc = "open html in zen", for = "linux" },
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = [ "pdf", "open" ] },
    { mime = "text/html", use = [ "html", "open", "edit" ] },
    { url = "*.htm*", use = [ "html", "open", "edit" ] },
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
